-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 17 Jan 2022 pada 09.16
-- Versi server: 10.4.19-MariaDB
-- Versi PHP: 7.4.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `judul`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `admin`
--

CREATE TABLE `admin` (
  `id_admin` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data untuk tabel `admin`
--

INSERT INTO `admin` (`id_admin`, `username`, `password`) VALUES
(2, 'admin', '$2y$10$F8m/jDXVqVwCWEPW7vZ83eWL7L5IGELW/iBxCe7NH2L21WCPCE.j6'),
(4, 'hafidh', '$2y$10$qJp7aBsb6egUpQbziXIOUefYHco5T/H1Fz06em6quacyQ3RU9dA0u');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tb_judul`
--

CREATE TABLE `tb_judul` (
  `id_judul` int(11) NOT NULL,
  `judul` text NOT NULL,
  `nama` varchar(25) NOT NULL,
  `nim` int(11) NOT NULL,
  `tahun` int(4) NOT NULL,
  `abstrak` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data untuk tabel `tb_judul`
--

INSERT INTO `tb_judul` (`id_judul`, `judul`, `nama`, `nim`, `tahun`, `abstrak`) VALUES
(22, 'PERANCANGAN JARINGAN HOTSPOT MENGGUNAKAN MIKROTIK PADA UPT TEKNOLOGI INFORMASI DAN KOMUNIKASI UNIVERSITAS MALIKUSSALEH', 'Yulita', 180170054, 2021, 'Di UPT TIK Universitas Malikussaleh terdapat layanan akses internet dimana seluruh kegiatan yang ada ditempat tersebut membutuhkan akses internet. Hotspot merupakan jaringan internet tanpa kabel dan bisa diakses oleh semua perangkat bahkan komputer desktop. Hotspot juga dapat digunakan sehari-hari dan dapat dilewati dari pusat trafik paket data dalam jumlah tertentu. Satuan kecepatan Hotspot per paket data adalah bit per detik (bps). Hotspot diukur batas kecepatan transfer dari jumlah konsumsi paket data per satuan waktu, serta kapasitas atau daya tampung kabel Ethernet disebut Bandwidth. Sampai saat ini, penggunaan jaringan Internet sesama pengguna dapat saling berebut paket ini tanpa berhenti dan tanpa batas, sehingga mengakses Internet akan terasa menyulitkan jika dipakai selamanya Tujuan dari penulisan laporan ini adalah untuk merancang. jaringan menggunkan mikrotik, dan mengkonfigurasi batas kecepatan internet mikrotik untuk memaksimalkan pengguna internet pada UPT TIK Universitas Malikussaleh. Perancanagan jaringan mikrotik sudah diketahui oleh manajemennya, untuk itu menggunakan Bandwidth dan Access Point Hotpsot dari Mikrotik RouterOS. Penulis berinisiatif untuk melakukan suatu perancangan jaringan Mikrotik pada UPT TIK Universitas Malikussaleh, caranya mendaftarkan melalui admin, admin membuat user hotspot, kemudian mengkonfigurasi kecepatan jaringan atau bandwidth dengan menggunakan aplikasi Winbox. Perancangan bangun jaringan ini diharapkan dapat membantu untuk mengoptimalkan badnwidth dari Mikrotik UPT TIK Universitas Malikussaleh.\r\n\r\nKatakunci: Hotspot, MikrotikOS Bandwidth, AccesPoint'),
(23, 'SISTEM INFORMASI PENDATAAN ARSIP SURAT KEPUTUSAN KANTOR SEKRETARIAT DAERAH KOTA LHOKSEUMAWE', 'Maya Safira', 180170026, 2021, 'Dalam proses moderninasisasi Administrasi, maka diperlukan implementasi system informasi yang dapat menunjang seluruh aktifitas adminitratif yang ada pada sebuah instnasi, Lembaga atau pun perusahaan. Pada kantor dinas Sekretariat Kota Lhokseumawe, masih adanya metode manajemen arsip surat konvensional yang dimana pencatatan arsip masih dilakukan dengan menggunakan buku dan alat tulis. Hal ini sering kali menimbulkan banyak masalah, seperti kehilangan dokumen ,kerusakan atau dokumen yang tidak terdata. Selama menjalani kerja praktek, penulis berusaha untuk mengembangkan sebuah aplikasi yang dapat mendata seluruh arsip yang ada pada instansi tersebut. Kemudian akan di simpan dalam database dan dapat di akses kapan saja dan dimana saja. Hasilnya, banyak manfaat yang diberikan untuk instansi, seperti pendataan arsip lebis terstruktur dan rapi.\r\n\r\nKata Kunci: Surat, Pendataan, Arsip, Database'),
(25, 'PERANCANGAN SISTEM INPUTAN DATA OTOMATIS BERBASIS WEB PADA KANDATEL LHOKSEUMAWE', 'Al Munawar', 190170167, 2021, 'Sistem inputan data otomatis merupakan sebuah tujuan yang sangat penting bagi sebuah instansi atau perusahaan untuk mencapai tujuan, hal ini berkaitan dengan hematnya waktu dan berdampak pada kinerja karyawan-karyawan, oleh karena itu, perlu adanya sistem inputan data secara otomatis agar semua kebutuhan untuk inputan data berbasis web bisa tersesuaikan dengan cepat dan tidak memakan waktu yang lama agar kinerja tercapai dengan waktu yang cepat. Pada kantor Kandatel Lhokseumawe sistem inputan data yang digunakan masih dalam proses manual menggunakan localhost yang berdampak efisiensi dan efektifitas pendataan, pencarian data sekaligus rekap data yang membutuhkan waktu yang relatif lama. Maka dari itu Sistem inputan data otomatis berbasis web ini bisa menghemat sekaligus memakan waktu yang singkat dan cepat pada kantor Kandatel Lhokseumawe dan memudahkan karyawan dalam proses penginputan data pelanggan kedalam basis web tersebut. Dan dengan adanya sistem inputan data secara otomatis ini membuat para karyawan pada Kandatel Lhokseumawe bisa dengan mudah dan praktis dalam pengaplikasian berupa data yang akan di inputkan kedalam sistem sehingga tidak akan terjadi kesalahan yang fatal atau data yang tidak terkirim ke semua laporan. Sistem inputan data otomatis ini juga mencakup ke grup telegram yang mengarah pada tujuan pengiriman laporan data akhir yang langsung dapat dengan mudah diterima dan dilaporkan kepada supervisor plasa dan kakandatel lhokseumawe langsung dengan metode otomatis, sistem inputan data ini merupakan dari salah satu hasil dari permasalahan yang terjadi selama ini di kandatel lhokseumawe karena permasalahan yang sama berulang kalinya terjadi dan sekarang dengan adanya ini mungkin bisa membuat sistem ini menjadi jauh lebih mudah untuk digunakan dan sangat bermanfaat untuk pengoperasian sistem data pada Telkom Kandatel Lhokseumawe.\r\n\r\nKata Kunci : Sistem Informasi, Inpuan Data Otomatis, Berbasis Web'),
(26, 'SISTEM INFORMASI PERPUSTAKAAN BERBASIS WEB PADA PERPUSTAKAAN SMK NEGERI 2 LHOKSEUMAWE', 'Shahlan', 181070031, 2021, 'Sistem Informasi Perpustakaan adalah sebuah sistem informasi yang dapat membantu proses pelayanan di sebuah perpustakaan. Saat ini Perpustakaan SMK Negeri 2 Lhokseumawe belum memiliki sistem yang efisien dan dapat dipakai secara bersamaan oleh pustakawan untuk mengelola data buku serta mencatat peminjaman buku. Dengan dibuatnya Sistem Informasi Perpustakaan, tentu dapat mempermudah petugas dalam menjalankan tugasnya. Sistem Informasi Perpustakaan ini sudah berbasis web dan menggunakan database mySQL sehingga dapat diakses melalui banyak perangkat dan pengolahan database buku menjadi lebih efesien.\r\n\r\nKata Kunci: Sistem informasi, web, perpustakaan, MYSQL, database.'),
(27, 'SISTEM INFORMASI PENDATAAN BANTUAN LOGISTIK DI KANTOR BADAN PENANGGULANGAN BENCANA DAERAH (BPBD) KABUPATEN ACEH UTARA', 'Nurul Aula', 1801870062, 2021, 'Badan Penanggulangan Bencana Daerah (BPBD) Kabupaten Aceh Utara merupakan instansi yang menanggulangi bencana di Kabupaten Aceh Utara Kebutuhan akan informasi sangat meningkat seiring perkembangan teknologi dan informasi yang semakin pesat saat ini serta menghasilkan inovasi-inovasi baru yang senantiasa terus berkembang ke arah yang lebih baik. Untuk mendapatkannya haruslah didukung dengan suatu teknologi informasi yang tepat dan berdaya guna serta relevan untuk penerapannya. Bantuan logistik merupakar. sumber daya utama yang dibutuhkan di BPBD Kabupaten Aceh Utara masih bersifat manual. Tujuan dari penelitian ini adalah untuk mengoptimalkan proses pengelolaan data logistik dan data penyaluran bantuan logistik di BPBD Kabupaten Aceh Utara. Hasil penelitian menunjukkan dengan adanya sistem informasi pendataaan bantuan logistik dapat membantu kinerja pegawai BPBD Kabupaten Aceh Utara dan dapat mengoptimalkan proses pengelolaan datar logistik dan data penyaluran bantuan logistik bagi korban bencana di kabupaten Aceh Utara. Sistem ini dibuat menggunakan bahasa pemrograman PHP dan menggunakan basis data MySQL. Karakteristik pengguna yaitu Admin merupakan pelaku yang bertugas melakukan pendataan barang masuk atau barang keluar dalam setiap kegiatan penanggulangan bencana. Berdasarkan hasil uji kelayakan pada tiap karakteristik pengguna didapatkan hasil bahwa sistem informasi pendataan stok BPBD ini mampu memberikan informasi yang lebih efisien.\r\n\r\nKata Kunci: Sistem Informasi, Logistik, Pendataan, Barang, BPBD.'),
(28, 'SISTEM INFORMASI PENGGAJIAN KARYAWAN PADA KANTOR WALI NAGARI MATUA MUDIAK', 'Annisa Azhari', 160170037, 2019, 'Pada masa sekarang ini, pengolahan data dan informasi membutuhkan kecepatan dan keakuratan. Untuk mendapatkannya haruslah didukung dengan suatu teknologi informasi yang tepat dan berdaya guna serta relevan untuk penerapannya. Kantor Wali Nagari Matua Mudiak merupakan sebuah perusahaan yang mengurusi semua aspek yang ada di desa dan memberikan pelayanan kepada masyarakat. Dalam melakukan proses penggajian kepada karyawannya dan membuat laporan gaji sebagai pertanggung jawaban kepada kepala kantor. Proses pencatatan dan perhitungan gaji. Kantor Wali Nagari Matua Mudiak telah menggunakan sistem penggajian karyawan, akan tetapi masih mempunyai kelemahan yaitu memerlukan waktu yang lama untuk pengimputan data, tidak bisa mencari data karyawan dan tidak bisa mencetak slip gaji karyawan. Dalam menyelesaikan masalah tersebut, penulis merancang pengembangan sistem tersebut menggunakan pemodelan Unified Modeling Language (UML), Personal Home Page (PHP) dan XAMPP sebagai web server, menggunakan basis data dari MySQL, Sublime Text untuk pengkodean aplikasi, serta HyperText Markup Language (HTML) dan CSS untuk membuat tampilan aplikasi. Dengan adanya Sistem Informasi Penggajian Karyawan. Kantor Wali Nagari Matua Mudiak ini, staff akan bisa melakukan menginputan data karyawan, melakukan pencarian data karyawan, melihat data gajian karyawan dan mencetak laporan slip gaji karyawan dengan cepat dan efisien.\r\n\r\nKata kunci: sistem informasi, penggajian, UML, web'),
(29, 'SISTEM INFORMASI PENDATAAN DISTRIBUSI PUPUK PADA PT PUPUK ISKANDAR MUDA', 'Siti Sarah', 160170003, 2019, 'Sistem Informasi Pendataan Distribusi pada PT Pupuk Iskandar Muda sebagai sistem pendukung kinerja karyawan kegiatan operasionalnya secara lebih efisien dan efektif. Jadi untuk mencari data yang memang sudah pernah di input ke perusahaan sangat lah banyak. Sehingga pegawai sangatlah sulit untuk mencari data tersebut. Oleh sebab itu penulis mencoba merancang sebuah sistem informasi Pendataan Distribusi pada PT PIM untuk mengurangi kesalahan yang mungkin terjadi pada saat bekerja dan juga dapat memberikan informasi secara komputerisasi dan dapat mempercepat pekerjaan dalam pendataan serta memudahkan proses pencarian data distribusi yang ada di kantor.\r\n\r\nKata kunci: Sistem, Informasi, Data'),
(30, 'PENGEMBANGAN SISTEM INFORMASI PENGARSIPAN BERBASIS WEB PADA SATUAN KERJA HUMAS POLDA ACEH', 'FAKHRURRAZI', 180170100, 2021, 'Seiring dengan perkembangan zaman, kebutuhan akan teknologi informasi sangat dibutuhkan dalam berbagai sektor kerja guna mempermudah kerja dan memperoleh informasi serta data yang relevan, akurat dan efisien. Pada Bidang Humas Polda Aceh Banyak sekali pekerjaan yang masih dilakukan secara manual, baik itu pendataan serta backup data surat masuk dan keluar di Divisi Humas Polda Aceh masih dilakukan secara manual Oleh karena itu, dibutuhkan sebuah sistem yang memadai dalam sistem, sehingga penulis mencoba membuat sebuah Pengembangan Sistem Informasi Pengarsipan Berbasis WEB Pada Satuan Kerja Humas Polda Aceh yang lebih optimal dan terorganisir dengan baik. Langkah-langkah yang digunakan dalam penelitian ini adalah analisis kebutuhan, perancangan sistem dan pengujian sistem. Perancangan sistem ini dirancang dengan menggunakan diagram terstruktur yaitu dengan Diagram Konteks, digram arus data atau disebut dengan Data Flow Diagram (DFD), Entity Relationship Diagram (ERD) dan perancangan database atau disebut desain file menggunakan MySQL. Sedangkan untuk pengumpulan data menggunakan cara dengan observasi, wawancara dan studi pustaka. Sedangkan untuk software menggunakan bahasa. pemograman PHP/XAMPP Control Panel v3 2.1. Dengan pembuatan dan pengembangan sistem informasi ini diharapkan mampu mengurangi masalah yang terjadi dalam pendataan data surat masuk dan surat keluar, membantu mempermudah staff anggota polri dalam proses pendataan tanpa harus ke ruang administrasi Humas, serta membantu proses kerja dalam memperoleh informasi dan data yang relevan, akurat dan efisien.\r\n\r\nKata Kunci Sistem Perancangan, Diagram Terstruktur, MYSQL, PHP XAMPP. DFD'),
(31, 'PERANCANGAN SISTEM INFORMASI HELPDESK PADA KANTOR UPT TIK UNIVERSITAS MALIKUSSALEH', 'Nurqamarina', 180170039, 2021, 'Penggunaan teknologi merupakan hal penting untuk meningkatkan efisiensi dalam melakukan suatu pekerjaan Di dalam lingkup kerja Universitas Malikussaleh, penggunaan teknologi informasi kepada semua civitas akademika sangat banyak manfaatnya Dan gangguan-gangguan yang dialami oleh pengguna apabila tidak ditangan akan berdampak pada kinerja dan proses belajar mengajar akan terganggu Oleh karena itu dibutuhkan sistem informasi helpdesk yang dapat digunakan sebagai tempat pertama yang harus dihubungi oleh pengguna bila mereka mendapatkan masalah baik itu jaringan atau lainnya. Sistem informasi helpdesk dibuat oleh penulis dengan tampilan yang menarik untuk memudahkan pengguna dalam pelaporan pertanyaan/keluhan secara online, helpdesk berbasis web dibuat dengan beberapa software pendukung yaitu salah satunya adalah PHP dan MySQL, PHP sebagai bahasa pemrograman yang mudah di mengerti oleh programmer web serta bersifat Open Source dan MySQL sebagai sistem manajemen database yang dapat diandalkan dan penggunaannya mudah untuk dipahami\r\n\r\nKata Kunci : Sistem Informasi, Helpdesk, PHP,MySQL'),
(32, 'APLIKASI PENGAJUAN CUTI ONLINE PEGAWAI BALAI WILAYAH SUNGAI SUMATERA 1 BERBASIS WEB', 'Danish Qalyubi', 161070119, 2019, 'Kebutuhan akan informatika sangat meningkat seiring perkembangan teknologi dan informasi yang semakin pesat saat ini serta menghasilkan inovasi - inovasi baru yang senantiasa terus berkembang ke arah yang lebih baik. Untuk mendapatkannya haruslah didukung dengan suatu teknologi informatika yang tepat dan berdaya guna serta relevan untuk penerapannya. Kantor Balai Wilayah Sungai Sumatera I merupakan sebuah perusahaan Pemerintah yang mengurusi semua Wilayah Sungai, Pantai Dan Irigasi kewenangan Pusat Daerah Aceh.Kerja Praktek ini terfokus pada bidang Perencanaan dan program BWS SI,Bidang tersebut memberikan pelayanan kepada instansi - instansi dalam penyediaan data dan pembuatan peta Daerah Irigasi. Berdasarkan hasil observasi yang dilakukan penulis menemukan beberapa hal yang menjadi masalah di dalam Bidang perencanaan dan Program Balai Wilayah Sungai Sumatera I.adapun dari segi sumber daya manusia (SDM) untuk menguasai teknologi yang ada karena dari pada itu penulis berinisiativ untuk membuat Aplikasi atau Sistem Informasi untuk pengajuan cuti online di karenkan pegawai BWS SI sering keluar kota karena mengadakan surve lapangan jadi ketika aplikasi ini nantinya ada mungkin bisa lebih bermanfaat untuk pegawai karena tidak perlu harus ke kantor untuk mengajukan cuti tapi biasa menggunakan system atau aplikasi yg sudah di rancang oleh penulis dan tidak banyak memakan waktu pegawai untuk harus ke kantor untuk mengajukan cuti jadi waktu pun menjadi lebih efektif. penulis merancang pengembangan sistem tersebut menggunakan pemodelan Unified Modeling Language (UML),Personal Home Page (PHP) dan XAMPP sebagai web server, menggunakan basis data dari MySQL, Sublime Text untuk pengkodean aplikasi, serta HyperText Markup Language (HTML) dan CSS untuk membuat tampilan aplikasi.\r\n\r\nKata kunci: sistem informasi, rekapitulasi, DFD, web'),
(33, 'SISTEM INFORMASI KENAIKAN JABATAN PEGAWAI PADA PT. TELKOM INDONESIA (TBK) WITEL ACEH', 'ASRIZAL', 140170026, 2017, 'Komputer telah menjadi alat yang sangat penting dalam pengolahan data untuk menanggulangi keterlambatan kinerja karyawan baik dalam pembuatan laporan maupun dalam hal pengolahan data lainnya, sehingga banyak pekerjaan yang dapat diselesaikan dalam waktu yang singkat Aplikasi ini dirancang menggunakan bahasa pemrograman PHP dan menggunakan database MySQL. Sistem Informasi Kenaikan Jabatan Pegawai Sistem adalah suatu sistem software yang akan membantu proses operasional perusahaan dengan menerapkan tertib administrasi kenaikan jabatan pegawai mulai dari Pencatatan dari data pegawai, jabatan, bagian, sampai dengan penyimpanan. Selain itu, kinerja perusahaan tersebut akan semakin meningkat seperti halnya juga pada PT Telkom Indonesia (Tbk) Witel Aceh yang bergerak di bidang pelayanan jasa informasi dan komunikasi (Infokom), dengan tugas pokok membangun, mengusahakan, dant mengembangkan pelayanan dalam bidang pegawai dan informasi tertulis, baik masalah jabatan maupun kenaikan jabatan\r\n\r\nKata Kunci Sistem Informasi, PT. Telkom Witel Aceh, PHP, MySQL'),
(34, 'IMPLEMENTASI SURVEI INDEKS KEPUASAN MASYARAKAT (IKM) BERBASIS WEB MENGGUNAKAN PHP PADA KANTOR PENGADILAN NEGERI LHOKSEUMAWE KELAS IB', 'KARIMULLAH', 180170094, 2021, 'Pengolahan data dan informasi membutuhkan kecepatan dan keakuratan data serta survei untuk mengetahui tingkatan kinerja tersebut semakin baik atau sebaliknya, untuk mendapatkannya, maka dibutuhkan suatu teknologi informasi survei yang dapat menunjang pekerjaan agar pekerjaar. menjadi lebih efektif dan efesien. Pengadilan Negeri Lhokseumawe merupakan sebuah kantor pemerintahan yang berjalan di bidang pengadilan dan memberikan layanan kepada masyarakat dalam penyediaan jasa yang berhubungan dengan pengadilan hukum yang berlaku. Proses pengelolaan data survei Pengadilan Negen Lhokseumawe kelas IB telah menggunakan sistem data pengolahan survei, akan tetapi masih memiliki kelemahan yaitu memerlukan waktu yang lama dalam melakukan pencarian data survey atau melihat laporan survei tersebut. Dalam menyelesaikan masalah tersebut, penulis merancang pengembangan sistem dengan menggunakan pemodelan Unifield Modeling Language (UML), Personal Home Page (PHP) dan XAMPP sebagai web server, menggunakan basis data data MySQL, Visual Studio Code untuk pengkodean aplikasi, serta HyperText Markup Language (HTML) dan CSS untuk membuat tampilan aplikasi. Dengan adanya aplikasi Survei Indeks Kepuasan Masyarakat di Pengadilan Negeri Lhokseumawe kelas 1B ini, staff akan bisa lebih mudah dapat mengecek hasil survei tentang bagaimana pendapat masyarakat mengenai pengalaman dalam memperoleh transparansi biaya, peraturan dan transaksi tentang perkara yang terjadi secara mudah\r\n\r\nKata kunci: Proses Survei Indeks Kepuasan Masyarakat (IKM) Pengadilan Negeri Lhokseumawe kelas 1B, Pemograman PHP, MySQL, Basis data, Web'),
(35, 'SISTEM INFORMASI SURAT PERINTAH PERJALANAN DINAS (SPPD) ONLINE BERBASIS WEB PADA KANTOR DPRD KOTA MEDAN', 'MEISIN', 180170107, 2021, 'Seiring dengan perkembangan zaman, kebutuhan akan teknologi informasi sangat dibutuhkan dalam berbagai sektor kerja guna mempermudah kerja dan memperoleh informasi serta data yang relevan, akurat dan efisien. Pada DPRD Kota Medan, Surat Perintah Perjalanan Dinas (SPPD) belum terorganisir dengan baik, dimana masih dilakukan secara manual, yaitu pegawai masih mencatat surat yang masuk dan surat yang keluar pada sebuah buku. Pendataan data seperti ini dapat mempersulit pegawai dalam pendataan dan pembuatan laporan, sehingga hal ini dapat memperlambat dan menghambat kerja, serta data dan informasi yang diperoleh kurang akurat, kurang efektif dan efisien. Oleh karena itu, dibutufikan sebuah sistem yang memadai dalam sistem Informasi Surat Perintah Perjalanan Dinas (SPPD), sehingga penulis mencoba membuat sebuah Sistem Informasi Sistem Informasi Surat Perintah Perjalanan Dinas (SPPD) Online Berbasis WEB Pada DPRD Kota Medan yang lebih optimal dan terorganisir dengan baik. Langkah-langkah yang digunakan dalam penelitian ini adalah analisis kebutuhan, perancangan sistem dan pengujian sistem. Perancangan sistem ini dirancang dengan menggunakan diagram terstruktur yaitu dengan Diagram Konteks, digram arus data. atau disebut dengan Data Flow Diagram (DFD), Entity Relationship Diagram. (ERD) dan perancangan database atau disebut desain file menggunakan MySQL Sedangkan untuk pengumpulan data menggunakan cara dengan observasi, wawancara dan studi pustaka. Sedangkan untuk software menggunakan bahasa pemograman PHP/XAMPP Control Panel v3.3.0. Dengan pembuatan dan perancangan sistem informasi ini diharapkan mampu mengurangi masalah yang terjadi dalam pendataan data barang masuk dan barang keluar serta membantu proses kerja dalam memperoleh informasi dan data yang relevan, akurat dan efisien.\r\n\r\nKata Kunci: Sistem Informasi, Diagram Terstruktur, MYSQL, PHP/XAMPP'),
(36, 'SISTEM INFORMASI BARANG ALAT TULIS KANTOR (ATK) PADA DINAS KOMUNIKASI DAN INFORMATIKA KABUPATEN LABUHANBATU SELATAN BERBASIS WEB MENGGUNAKAN PHP FRAMEWORK CODEIGNITER', 'GARTIO PRADANA RITONGA', 180170088, 2021, 'Sistem Informasi Barang Alat Tulis Kantor adalah sebuah sistem informasi yang dapat membantu pendataan ketersediaan Barang Alat Tulis Kantor Saat ini Kantor Dinas Komunikasi dan Informatika Kanupaten Labuhanbatu Selatan membutuhkan sistem informasi yang dapat membantu dalam pendataan ketersediaan Barang Alat Tulis Kantor. Pendataan Barang Alat Tulis Kantor tersebut masih menggunakan cara manual dan sering terjadi kesalahan dalam pendataan Barang Masuk dan Barang Keluar. Sistem informasi Barang Alat Tulis Kantor ini sangat diperlukan, untuk mempermudah administrator dalam. pendataan Barang Masuk dan Barang Keluar. Sistem informas: Barang Alat Tulis Kantor ini memberikan kontribusi baik bagi instansi Tahapan perancangan yang digunakan meliputi perancangan context diagram, data flow diagram, entity relationship diagram, dan database table. Sistem informasi barang alat tulis kantor membuat pendataan barang masuk dan barang keluar lebih cepat dan efisien. Sistem informasi ini dapat diakses dan dijalankan secara localhost\r\n\r\nKata kunci: Sistem Informasi, Barang Masuk, Barang Keluar'),
(37, 'SISTEM INFORMASI RANCANGAN LOUNCHING COMMAND CENTER DINAS KOMUNIKASI DAN INFORMATIKA KABUPATEN ACEH TENGAH`', 'Tiara Nanda Juwita', 180170125, 2021, 'Command Center au pusat komando kendall pelayanan informasi publik merupakan salah satu fasilitas yang diperlukan oleh pemerintah daerah dalam menjalankan Manajemen Krisis (Crisis Management), atau titik-titik kritis yang membutuhkan pelayanan secara cepat dan mudah. Command Center dapat diartikan sebagai lokasi atau tempat untuk menyediakan perintali, koordinasi, dan pembuatan keputusan dalam mendukung respon suatu kejadian penting Dengan dioperasikannya Aceh Tengah Command Center ini, nantinya pimpinan dapat memonitor seluruh pelayanan yang diberikan kepada masyarakat melalui teknologi informasi, memudahkan interaksi diantara OPD dans menghubungkan dengan berbagai aplikasi Selain peluncuran Aceh Tengali Command Center. Bupati Shahela dalam kesempatan ini juga sekaligus meresmikan infrastruktur jaringan kabel fiber optik (FO) Portal Layanan Acehi Tengal Smart Regency, dan Aplikasi Aceh Tengah Satu Data, (Smart Connectivity) Sistem Informasi Terpadu serta membuka secara simblolis Focus Group Discussion (FGD) Penysisaman Rencana Induk Smar CHY Kabupate Aceh Tengah Melalui tampilan dashboard portal layanan Aceh Tengah Smart Regency Smart City dan aplikasi Aceh Tengah Sam Data (Smart Connectivity) sistem informasi terpadu. Portal tersebut merupakan dashboard utama antar aplikasi Aplikasi Aceh Tengah Satu Data (Smart Connectivity) adalah sistem manajemen data yang terintegrasi untuk kebutuhan analisis statistik pusat informasi pembangunan dan sebagai bahan bagi pemerintah daerah dalam perencanaan, evaluast, pelaporan, dan pengambilan keputusan secara bijaksana dan profesional.\r\n\r\nKata Kunci: Command Center, Portal Layanan Aceh Tengah'),
(38, 'Penerapan Teknologi Fiber Optik Pada UPT TIK Universitas Malikussaleh', 'Yuri Kharisma', 180170053, 2021, 'Kabel Jaringan Fiber Optic Kabel Fiber Optik saluran transmisi atau sejems kabel yang terbuat dari kaca atau plastikyang sangat halus dan lebih kecil dari sehelai rambut, dan dapat digunakan untuk mentransmisikan sinyal cahaya dari suatu tempat ke tempat lain Sumber cahaya yang digunakan biasanya adalah laser atau LED Kabel ini berdiameter lebih kurang 120 mikrometer jenis adaptor fiber optik ini tersedia dalam jenis single mode dan multimode, serta Simplex dan duplex SC adapter fiber optik dengan perumahan (housing) plastik Fusion splicer atau sering dikenal sebagai alat untuk menyambungkan serat optik ini merupakan salah satu alat yang digunakan untuk menyambungkan sebuah core serat optik, dimana serat tersebut terbuat berbasis kaca, dan mengimplementasikan suatu daya listrik yang telah dirubah menjadi sebuah media sinar berbentuk laser truktur kabel Fiber Optik berbeda dengan kabel multipair tembaga, jika pada kabel tembaga dikenal istilah pasangan atau pair, maka pada kabel fiber optik tidak dikenal istilah pasangan atau pair Secara umum, struktur kabel Fiber Optik terdiri dan Tube dan Fiber (atau istilah umumnya dilapangan disebut dengan \"core\"). Pada Tube dan Core untuk mengenali urutan diberi warma yang berbeda Nilai redaman yang di hasilkan oleh Fusion splice loss maksimum 0,15 dB, sedangkan nilai te faman untuk Mechanical splice loss maksimum 0,2 dB. Nila redaman untuk Connector maksimum 0,25 dB (Individual), sedangkan nilai redaman untuk connector secara Berpasangan (terminasi) adalah maksimum 0,7 dB.\r\n\r\nKata kunci : Kabel Jaringan Fiber Optic, fusion splicer'),
(39, 'PERANCANGAN SISTEM INFORMASI PENCATATAN SURAT KELUAR DAN SURAT MASUK (SUKEM) BERBASIS WEB DI KANTOR BKPSDM KABUPATEN PADANG LAWAS UTARA', 'LINA MARDIANA HARAHAP', 180170126, 2021, 'Pencatatan agenda surat keluar dan surat masuk yang ada di BKPSDM Kab Padang Lawas Utara masih bersifat manual, yama dicatat didalam buku besar Hal itu dapat menyulitkan pegawai dalam mencatat, menyimpan buku agenda, dan mencari surat apabila diperlukan Kesulitan dan kerumitan dalam pengolahan surat itu dapat diatasi dengan memanfaatkan kemajuan teknologi yaitu membuat sebuah Sistem informasi yang dapat mengolah pencatatan surat sehingga dapat membantu proses pengambilan keputusan dengan cepat Sistem informasi ini dibangun dengan bahasa perirograman Php dan database Mysql yang mendukung dalam pembuatan aplikasi berhasis web. Aplikasi ini dirancang dengan berbasis web karena lebih hemat dengan tidak harus menggunakan banyak perangkat besar, selain itu sistem ini dapat diakses dimana pun. Hasil yang diperoleh dari implementasi sistem informasi pencatatan surat keluar dan surat masuk im yaitu memudahkan pegawai di bidang sub bagian umum dalam mengelola pencatatan surat yang dulunya manual sekarang menjadi digital, serta sangat membantu proses penyampaian informasi isi surat kepada instansi didalam maupun diluar dengan lebih cepat.\r\n\r\nKata kunci: Sistem Informasi, Surat, web, MySQL, PHP'),
(40, 'ANALISIS DAN PERANCANGAN SISTEM INFORMASI MANAJEMEN SURAT MASUK DAN SURAT KELUAR PADA KEBUN PT. DELIMA MAKMUR ACEH SINGKIL', 'Reza Alfian Chaniago', 170170019, 2020, 'Sistem Informasi Manajemen Surat Masuk dan Surat Keluar Pada PT. Delima Makmur merupakan suatu aplikasi yang dirancang dan dibuat untuk memudahkan karyawan/staff di Kantor dalam mengelola database surat. Adapun tujuan dari penelitian ini adalah untuk mengetahui bagaimana merancang dan membuat suatu sistem informasi yang mampu mengurangi masalah yang terjadi dalam pengelolaan surat pada Kantor Kebun PT Delima Makmur. Oleh karena itu penulis mencoba membuat suatu Sistem Informasi Manajemen Surat Masuk dan Surat Keluar pada PT. Delima Makmur. Sistem ini sangat penting karena dapat memudahkan para staff karyawan dalam mengelola semua surat yang masuk dan keluar di kantor. Sistem informasi ini menggunakan metode pengumpulan data dan berlanjut ke penggambaran diagram konteks, ERD DFD, dan tampilan desain antar muka impid dan output dari sistem im Sistem ini menggunakan bahasa pemograman PHP dengan Framework Codelgniter.\r\n\r\nKata Kunci: Sistem Informasi Surat, PHP. MySQL'),
(41, 'PERANCANGAN DAN IMPLEMENTASI SISTEM INFORMASI WISUDA PADA KANTOR UPT PUSKOM UNIVERSITAS MALIKUSSALEH', 'Umar Khalil', 150170043, 2018, 'Sistem Informasi Wisuda adalah sebuah sistem informasi yang dapat membantu proses pelaksanaan wisuda di sebuah universitas. Sistem ini dapat membantu mulai dari jadwal pelaksanaan kegiatan wisuda, pendaftaran peserta, verifikasi berkas, sampai laporan akhir kegiatan wisuda. Dengan membuat Sistem ini berbasis Web, tentu akan lebih memudahkan untuk twer agar dapat mengakses sistem ini kapan pun dan di mana pun. Selain bisa membantu proses pelaksanaan wisuda, sistem ini juga bisa menjadi sebuah media penyimpanan data-data kegiatan wisuda sebelumnya Ini akan sangat membantu jika user ingin membuat laporan kegiatan kegiatan terdahulu dengan bantuan sistem informasi wisuda ini.\r\n\r\nKata Kunci: Sistem Informasi, Wisuda, user, Web'),
(42, 'SISTEM INFORMASI PELAYANAN &amp; KELUHAN PELANGGAN DI PT. PLN (PERSERO) RAYON LHOKSUKON', 'MUHAJIR PRASETYO', 160170063, 2019, 'Pada masa sekarang ini, pengolahan data dan informasi membutuhkan kecepatan dan keakuratan. Untuk mendapatkannya haruslah didukung dengan suatu teknologi informasi yang tepat dan berdaya guna serta relevan untuk penerapannya. PT.PLN (Persero) Rayon Lhoksukon merupakan sebuah perusahaan yang mengurusi semua aspek kelistrikan dan memberikan pelayanan kepada masyarakat dalam penyediaan jasa yang berhubungan dengan penjualan tenaga listrik yang mana pada setiap hari nya ada keluhan dari pelanggan tentang gangguan dan keluhan lainnya mengenai penggunaan listrik. Proses pencatatan dan pengolahan data pelayanan & keluhan pelanggan di PT.PLN (Persero) Rayon Lhoksukon masih dilakukan secara manual dengan menggunakan Microsoft Excel sehingga data-data keluhan mudah hilang dan mengalami duplikat data. Dalam menyelesaikan masalah tersebut, penulis merancang pengembangan sistem dengan memaparkan kajian teori yang digunakan sebagai dasar penyusunan dan akan dibahas mengenai perancangan sistem informasi berbasis web dengan menggunakan PHP dan MySQL Mengenai hal ini, penulis akan membuat laporan tentang sistem informasi pelayanan dan keluhan dari pelanggan. Adapun tujuan. dari sistem informasi ini adalah untuk mempermudah staff atau karyawan divisi pelayanan pelanggan & adm dalam mendata serta melayani keluhan dari pelanggan PT.PLN (Persero) Rayon Lhoksukon sehingga memudahkan pegawai PT PLN (Persero) Rayon Lhoksukon untuk mendata dan melayani pelanggan dengan terstruktur.\r\n\r\n\r\nKata kunci Sistem, Informasi, Pelayanan, Keluhan, Pelanggan'),
(43, 'SISTEM INFORMASI GUDANG DI PT.PLN (PERSERO) AREA LHOKSEUMAWE', 'PUTRI ADITIA', 160170044, 2019, 'Pada PT.PLN (Persero) pendataan barang gudang sering dilakukan secara manual dengan melakukan pendataan barang gudang menggunakan media kertas sebagai bentuk pendataan, karena itu sering terjadi kekeliruan, kesalahan dan bahkan kehilangan data yang masih dibutuhkan di masa yang akan datang, sehinggal melambatkan kinerja, hal ini disebabkan karena tidak adanya sistem informasi gudang yang bertujuan untuk memberikan data yang akurat dan terpecaya serta memberikan laporan-laporan transaksi, seperti laporan data barang, laporan barang masuk, dan laporan barang keluar.\r\n\r\nKata Kunci: Sistem Informasi, Gudang'),
(44, 'SISTEM INFORMASI BARANG REJECT BPJS KETENAGAKERJAAN CABANG LHOKSEUMAWE', 'NUR AZIZAH', 160170045, 2019, 'Kantor BPJS KETENAGAKERJAAN Cabang Lhokseumawe merupakan suatu Instasnsi pemerintah yang bertujuan untuk melindungi para pekerja diseluruh Indonesia dari masalah kecelakaan kerja. Kantor BPJS KETENAGAKERJAAN Cabang Lhokseumawe memiliki asset kantor untuk menunjang kinerja para pegawainya. Dalam asset tersebut terdapat barang yang tidak terpakai lagi atau biasa disebut Barang Reject. Barang reject merupakan kategori barang yang tidak bisa dipakai lagi dan akan diberi tindakan apakah barang tersebut akan dijual, disimpan, atau dimusnahkan, namun, dari pihak kantor tersebut belum memiliki system informasi yang mendukung untuk mengatasi permasalahan barang reject tersebut Melihat Masalah tersebut penulis mencoba membuat suatu Sistem informasi Barang Reject. Dimana dalam system informasi tersebut pegawai Kantor BPJS KETENAGAKERJAAN Cabang Lhokseumawe dapat mengatur dan memilih tindakan apa yang patut diberikan pada. barang reject tersebut. Pembuatan System Informasi Barang Reject ini menggunakan bahasa pemrograman PHP dan MYSQL, serta aplikasi penunjang nya yaitu sublime text. Dengan adanya Sistem Informasi ini dapat mengatasi permasalahan Barang Reject di Kantor BPJS KETENAGAKERJAAN Cabang Lhokseumawe dengan mudah, aman, dan cepat.\r\n\r\nKata Kunci Sistem Informasi, Barang Reject, PHP, MYSQL, BPJS KETENAGAKERJAAN'),
(45, 'SISTEM INFORMASI ABSENSI KERJA PRAKTEK PADA PT. JASA RAHARJA (PERSERO) PERWAKILAN LHOKSEUMAWE', 'FIASARI ', 160170100, 2019, 'PT. JASA RAHARJA (Persero) Perwakilan Lhokseumawe merupakan Badan Usaha Milik Negara (BUMN) yang bergerak dibidang Penjaminan kecelakaan Saat ini dibutulikan upaya untuk membuat proses komputerisasi terhadap proses absensi kerja praktek (KP) untuk mempermudah perekapan absensi peserta KP dan pengolahan data peserta KP agar lebih efektif. Maka penulis bermaksud untuk mencoba menangani prosedur absensi dengan membuat suatu Sistem Informasi Absensi Kerja Praktek Dengan adanya perancangan dan program sistem informasi absensi kerja praktek berbasis web pada PT. JASA RAHARJA (Persero) Perwakilan Lhokseumawe maka prosedural pengisian absensi dengan manual di upgrade sehingga absensi kerja praktek dapat menghasilkan rancangan yang dapat meningkatkan keefisienan pengisian absensi karena sudah berbasis web.\r\n\r\nKata Kunci: Sistem Informas, PHP. Absensi, MySOL'),
(46, 'SISTEM INFORMASI BARANG MASUK DAN BARANG KELUAR GUDANG DI KANTOR DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL ACEH TIMUR', 'MALAHAYATI BINTI A.RAHMAN', 140170009, 2018, 'Sistem informasi gudang barang masuk dan barang keluar Kantor Dinas Kependudukan Dan Pencatatan Sipil Kabupaten Aceh Timur adalah sebuah Sistem Informasi yang beroperasi dalam hal pendataan barang masuk dan barang keluar gudang pada Kantor Dinas Kependudukan Dan Pencatatan Sipil Kabupaten Aceh Timur. Selama ini sistem yang digunakan di Kantor Dinas Kependudukan Dan Pencatatan Sipil Kabupaten Aceh Timur adalah sistem pencatatan manual. Namun seiring dengan kemajuan teknologi di bidang IT diperlukanlah pencatatan yang berbasis aplikasi komputer sehingga tidak hanya dapat memenuhi tantangan zaman, juga lebih kefungsinya dalam memudahkan pendataan Adapun pembuatan sistem ini dimulai dengan menganalisis sistem yang sedang berjalan di kantor tersebut dan membuat suatu sistem baru. Perancangan ini dimulai dari diagram prosedur dimana terdapat diagram konteks dan diagram alir data atau disebut dengan Data Flow Diagram (DFD) serta Entity Relationship Diagram (ERD) Merancang basis data (database) dan user interfacese bagai gamburan dasar tampilan sistem yang akan dibangun nantinya Sistem ini diharapkan dapat mempermudah staf keuangan baik dalam melakukan pendataan barang masuk dan barang keluar gudang maupun pembuatan laporan data barang masuk dan keluar gudang di Kantor Dinas Kependudukan Dan Pencatatan Sipil Kabupaten Aceh. Timur.\r\n\r\nKeyword:  Sistem, Informasi, Database, DFD, ERD'),
(47, 'SISTEM INFORMASI PENDATAAN CUTI PEGAWAI PADA KANTOR BPKD ACEH TAMIANG', 'MULIANI', 160170041, 2019, 'Sistem Informasi Pendataan Cuti Karyawan Pada Kantor Badan Pengelolaan Keuangan Daerah Aceh Tamang merupakan suatu aplikasi yang dirancang dan dibuat untuk memudahkan para karyawan/staff pada Kantor Badan Pengelolaan Keuangan Daerah Aceh Tamiang dalam pendataan cuti karyawan. Adapun tujuan dari penelitian ini adalah untuk mengetahui bagaimana merancang dan membuat suatu sistem informasi yang mampu mengurangi masalah yang terjadi dalam pendataan cuti karyawan pada Kantor Badan Pengelolaan Keuangan Daerah Aceh Tamiang Oleh karena itu, penulis mencoba membuat suatu Sistem Informasi Pendataan Cuti Karyawan Pada Kantor Badan Pengelolaan Keuangan Daerah Aceh Tamiang Sistem ini sangat penting karena dapat memudahkan para karyawan/staff dalam mendata cuti karyawan. Sistem informasi ini menggunakan a metode pengumpulan data dan berlanjut kepenggambaran diagram konteks, ERD DFD, dan tampilan desain input dan output dari sistem ini. Sistem ini menggunakan bahasa pemograman PHP.\r\n\r\nKata Kunci: Sistem Informasi, PHP, MySQL'),
(48, 'PENERAPAN SISTEM INFORMASI TRACER ALUMNI BERBASIS WEB DI FAKULTAS ILMU SOSIAL DAN ILMU POLITIK UNIVERSITAS MALIKUSSALEH', 'ULFA ILYATIN', 170170095, 2020, 'Tracer alumni merupakan studi pelacakan jejak lulusan atau jejak alumni, yang dilakukan kepada para mahasiswa setelah lulus. Tracer alumni bertujuan untuk mengetahui outcome pendidikan dalam bentuk transisi dari dunia pendidikan perguruan tinggi ke dunia kerja. Dalam penulisan laporan kerja praktek ini penulis melakukan analisa dengan menggunakan studi lapangan dan studi kepustakaan mengenai sistem pendataan alumni di Fakultas Ilmu Sosial dan Ilmu Politik Universitas Malikussaleh yang masih dilakukan secara manual, sehingga penulis memutuskan untuk membangun sebuah sistem informasi Tracer Alumni berbasis web yang dapat mempermudah pendaatan jejak mahasiswa yang sudah lulus, Sistem Tracer Alumni ini juga dapat menjadi salah satu penunjang untuk akreditasi perguruan tinggi. Sistem ini di rancang dengan menggunakan bahasa pemrograman PHP/Xampp dengan menggunakan diagram terstruktur, yaitu dengan Diagram Konteks, Data Flow Diagram (DFD), Entity Relationship Diagram (FRD) dan perancangan database menggunakan MySQL.\r\n\r\nKata Kunci: Sistem Informasi, Tracer, Alumni, PHP/Xampp, MySQL, Fakultas Ilmu Sosial dan Ilmu Politik.'),
(49, 'APLIKASI PENDAFTARAN MAGANG PADA DINAS KOMUNIKASI DAN INFORMATIKA KABUPATEN LANGKAT MENGGUNAKAN METODE WATERFALL', 'DEPI ELPINA TUMANGGOR', 160170061, 2019, 'Dinas Komunikasi dan Informatika (Diskominfo) Kabupaten Langkat merupakan Perangkat Daerah baru yang merupakan penggabungan Bagian Pengolahan Data Elektronik dan Santel, serta Bagian Komunikasi dan Informasi pada Setda Kabupaten Langkat. Dalam pemerintahan, sudah pasti sangat membutuhkan teknologi informasi yang dapat mempermudah pekerjaan birokrasi pemerintahan. Intranet menjadi alat bagi setiap pegawai di lingkungan Dinas Komunikasi dan Informatika Kabupaten Langkat untuk melakukan interaksi dan menyelesaikan pekerjaan. Seperti yang diketahui setiap tahunnya akan ada kagiatan magang yang dilakukan oleh Siswa/i ataupun Mahasiswa/i. Magang atau istilah untuk anak SMK PKL (Praktek Kerja Lapangan) merupakan kegiatan akademik yang diikuti oleh siswa Sekolah Menengah Kejuruan (SMK) dan juga Mahasiswa/i. Diskominfo Langkat menjadi salah satu tempat para siswa/i atau mahasiswa/i untuk melaksanakan Magang, hal tersebut mengakibatkan beberapa masalah dalam pengkoordinasian yang dilakukan oleh pegawai Diskominfo Langkat. Website intranet pendaftaran magang, menjadi salah satu dari sekian banyak solusi untuk membantu menyelesaikan pekerjaan pegawainya. Dalam penelitian ini penulis bermaksud untuk membuat satu Aplikasi Pendaftaran Magang di Dinas Komunikasi dan Informatika Kabupaten Langkat Menggunakan Bahasa Pemrograman PHP & MySQL. Sistem ini digunakan untuk mempermudah pegawai di lingkungan kabupaten langkat maupun calon peserta magang untuk mendaftar maupun menerima Siswa/i dan Mahasiswa/i yang akan magang di Dinas Komunikasi dan Informatika Kab.Langkat, sehingga tidak perlu lagi datang langsung ke kantor yang bersangkutan dan tidak harus melalui proses yang rumit. Dengan dikembangkannya sistem ini, diharapkan staff atau admin pada perusahaan tersebut bisa melakukan pekerjaan menjadi lebih efektif dan efisien. Metode waterfall merupakan metode yang sering digunakan penganalisa sistem pada umumnya. Inti dari metode waterfall adalah pengerjaan dari suatu sistem dilakukan secara berurutan atau secara linier. Jadi jika langkah ke-1 belum. dikerjakan, maka langkah ke-2 tidak dapat dikerjakan. Jika langkah ke-2 belum dikerjakan maka langkah ke-3 juga tidak dapat dikerjakan, begitu seterusnya. Dalam menyelesaikan masalah tersebut, penulis merancang pengembangan sistem dengan menggunakan metode Waterfall.\r\n\r\nKata Kunci: Magang, Aplikasi, Waterfall, PHP, Sistem.'),
(50, 'SISTEM INFORMASI PENDATAAN PENDUDUK PADA KANTOR CAMAT BANDA BARO', 'MURTADHA', 140170075, 2017, 'Kecamatan Banda Baro memiliki 1 (satu) Kemukiman yaitu Kemukiman Bandar Baru yang membawahi 6 (enam) Desa / Gampong yakni Gampong Jamuan, Alue Keurinyai, Ulee Nyeue, Cot Jabet, Paya Uleue dan Paya Dua. Namun, proses pendataannya masih dilakukan secara manual dan sederhana sehingga membutuhkan waktu yang lama untuk mencarinya saat data tersebut diperlukan kembali yang tentunya menjadi tidak efisien. Maka dari itu penulis membuat sistem informasi pendataan penduduk di Kantor Camat Banda Baro. Sistem ini mampu membantu mempermudah dan mempercepat proses pendataan penduduk. Pembuatan sistem informasi tersebut menggunakan metode pengumpulan data yang kemudian berlanjut ke tahap perancangan melalui penggambaran diagram konteks, DFD, ERD dan rancangan desain input dan Output dari sistem ini. Hasil yang diharapkan dari pembuatan sistem informasi ini dapat memberikan kemudahan bagi admin dalam melakukan pendataan penduduk serta kejelasan hasil laporan yang disampaikan admin kepada pimpinan, juga tentunya mempermudah bagi pihak-pihak tertentu mendapatkan informasi penduduk dengan cepat dan tepat di Kantor Camat Banda Baro.\r\n\r\nKata Kunci: Sistem Informasi, Diagram Könteks, DFD, ERD'),
(51, 'APLIKASI PENYIMPANAN DATA PENDAFTARAN AKTA KELAHIRAN DI KANTOR DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL ACEH TIMUR', 'CHAIRUNNISAH', 140170027, 2018, 'Aplikasi penyimpanan data pendaftaran akta kelahiran di kantor Dinas. Kependudukan Dan Pencatatan Sipil Aceh Timur masih menggunakan cara manual yaitu masih pencatatan data buku,sehingga mengalami banyak kendala Oleh karena itu dibutuhkan system informasi penyimpan data pendaftaran akta kelahiran yang memadai, untuk memproses data pendaftaran akta kelahiran secara otomatis dan menghasilkan informasi yang lebih efektif dan efisien Perancangan sistem informasi tersebut menggunakan metode pengumpulan data yang kemudian berlanjut kearah penggambaran diagram konteks, DFD, ERD dan rancangan desain input dan Output dari sistem ini Aplikasi ini membantu proses pencatatan dengan otomatisasi data pendaftaran serta membantu mempercepat proses pembuatan laporan tersebut.\r\n\r\nKata kunci : Data Pendaftaran, Sistem Informasi, Diagram Konteks, DFD, ERD'),
(52, 'SISTEM INFORMASI MANAJEMEN ASET KANTOR BERBASIS WEB PADA BPJS KESEHATAN KANTOR CABANG LHOKSEUMAWE', 'MUAZZINAH', 150170031, 2018, 'Seiring dengan perkembangan zaman, kebutuhan akan teknologi informasi sangat dibutuhkan dalam berbagai sektor kerja guna mempemudah kerja dan memperoleh informasi serta data yang relevan, akurat dan efisien. pada Kantor BPJS Kesehatan Kantor Cabang Lhokseumawe, manajemen aset belum terorganisir dengan baik dimana data aset masih dilakukan secara manual, yaitu petugas masih mencatat data aset dan data pemeliharaan aset pada selembar kertas. Pendataan data seperti ini dapat mempersulit petugas dalam pendataan dan pembuatan laporan, sehingga hal ini dapat memperlambat dan menghambat kerja serta data dan informasi yang diperoleh. kurang akurat, kurang efektif dan efisien. Oleh karena itu, dibutukan sebuah sistem yang memadai dalam sistem manajemen aset, sehingga penulis mencoba membuat sebuah Sistem Informasi Manajemen Aset Kantor Berbasis Web pada BPJS Kesehatan Kantor Cabang Lhokseumawe yang lebih optimal dan terorganisir dengan baik. Langkah-langkah yang digunakan dalam penelitian adalah ini adalah analisis kebutuhan, perancangan sistem dan pengujian sistem. Perancangan sistem ini dirancang dengan menggunakan diagram terstruktur yaitu dengan Diagram Konteks, diagram arus data atau disebut dengan Data Flow Diagram (DFD), Entity Relationship Diagram (ERD) dan perancangan database atau disebut desain file menggunakan MySQL. Sedangkan untuk pengumpulan data menggunakan cara dengan observasi, wawancara dan studi pustaka. Sedangkan untuk software menggunakan bahasa pemograman PHP/XAMPP Control Panel v3.2.1. Dengan pembuatan dan perancangan sistem informasi diharapkan mampu mengurangi masalah yang terjadi dalam pendataan data aset dan data pemeliharaan aset serta membantu proses kerja dalam memperoleh informasi dan data yang relevan akurat dan efisien.\r\n\r\nKata Kunci: Sistem Informasi, Diagram Terstruktur, MYSQL, PHP/XAMPP.'),
(53, 'SISTEM INFORMASI MONITORING KEGIATAN SATKER DI KANTOR PELAYANAN PERBENDAHARAAN NEGARA LHOKSEUMAWE', 'Fazilah Umaiva', 170170006, 2020, 'Sistem informasi Monitoring Kegiatan atau lebih dikenal dengan suatu aktivitas yang di laksanakan di dalam instansi yang menjadi acuan dalam mewujudkan komunikasi yang relevan dengan syarat-syarat yang berlaku. Kegiatan merupakan unit kerja yang dibentuk pegawai sebagai upaya memberikan informasi bagi SATKER maupun pegawai dan memperoleh pengetahuan akan instansi Dalam hal ini diharapkan dengan adanya suatu kegiatan yang tetap di lakukan para pegawai mampu meningkatkan kualitas terhadap pekerjaan masing-masing, dengan aturan yang sesuai dan berlaku. Secara berkala dengan adanya kegiatan membuat kinerjan menjadi produktivas, efisiensi, dan efektivitas.\r\n\r\nAdapun pembuatan sistem ini dimulai dengan melakukan observasi (pengamatan) langsung terhadap sistem yang digunakan oleh Gudang tersebut dan penulis membuat sistem yang baru berdasarkan kelemahan dari sistem yang digunakan sebelumnya. Perancangan sistem ini dimulai dengan membuat metode pengembangan sistem dengan model Waterfall, kemudian penulis menggunakan UML (Unifield Modeling Language) yang terdiri dari Use Case Diagram, Activity Diagram, Sequence Diagram dan Class Diagram sebagai diagram prosedur system. Sistem ini dibangun dengan menggunakan Bahasa pemrograman PHP dan MySql sebagai databasenya. Dengan adanya sistem ini diharapkan dapat memaksimalkan dan menambah efisiensi waktu para pegawai KPPN.\r\n\r\nKata kunci: Sistem, Informasi, UML, PHP. MySql'),
(54, 'ANALISIS SISTEM KOMUNIKASI SERAT OPTIK, FIBER TO THE HOME (FTTH) PADA PT. TELEKOMUNIKASI INDONESIA Tbk.', 'M Farhan Aulia Barus', 180170004, 2021, 'Jaringan kabel drop serat optik merupakan suatu serat optik pada jaringan FTTH yang dipasang dari ODP menuju OTP (Optical Termination Premises) yang terletak di rumah pelanggan. Pemasangan kabel drop Optik salah satu proses yang harus diperhatikan dalam membangun jaringan FTTH, karena kabel ini merupakan terminasi antara akhir antara ODP dan OTP yang berada di rumah. pelanggan. Kabel drop berfungsi untuk meneruskan sinyal optik menuju rumah pelanggan menggunakan standar tipe kabel yang tidak sensitif terhadap tekukan, hal ini dimaksudkan untuk mengantisipasi lokasi pemasangan kabel. Kegiatan praktek kerja lapangan bertujuan untuk melatih potensi mahasiswa di dunia kerja dan mengetahuai teknologi telekomunikasi pada dalam lingkup bisnis telekomunikasi. Menentukan alur kabel merupakan proses yang harus dilakukan sebelum pemasangan dilakukan, agar pemasangan dapat dilakukan tanpa gangguan dan mudah diperbaiki ketika mengalami kerusakan. Pemasangan kabel drop optik dimulai dari ODP Pole yang terletak di tiang, untuk menghubungkan. kabel drop optik dilakukan dengan menghubungkan konektor dengan kabel drop. kemudian dihubungkan dengan port pada ODP Pole. Setelah terhubung dengan ODP Pole, penarikan kabel drop dimulai, kabel ditarik menuju ujung atas. Penarikan kabel drop menuju beberapa tiang diharuskan memasang S-Clamp pada messenger wire untuk memperkuat dan melindungi drop core dari tekukan dan benturan yang dapat menyebabkan putusnya drop core. Kelenturan panjang kabel dalam pemasangan kabel drop 2% panjang jarak antar tiang. Kabel drop optik saat di rumah pelanggan disambungkan dengan fusion conneector kemudian dihubungkan menuju OTP. Pengukuran daya pada OTP harus memiliki nilai pada range -23 dBm -20,5 dBm.\r\n\r\nKata kunci : Sistem komunikasi serat optic, FTTH, ODP, OTP, Serat Optic.'),
(55, 'SISTEM INFORMASI PENGELOLAAN DATA PEGAWAI PADA BAGIAN TATA PEMERINTAHAN SEKRETARIAT DAERAH KOTA LHOKSEUMAWE', 'ELMA FITRIA ANANDA', 180170005, 2021, 'Bagian Tata Pemerintahan adalah unsur pembantu Asisten Pemerintahan dan Kesejahteraan Rakyat di bidang penyelenggaraan pemerintahan, yang bernaung di bawah SETDAKO LHOKSEUMAWE tetapi pada bagian Tata Pemerintahan proses mengelola dan penyimpanan informasi yang berhubungan dengan data profil pegawai masih dilakukan secara manual. Hal tersebut mengakibatkan pengkategorian yang kurang tepat, format data tidak konsisten, dan adanya duplikat, dapat mempersulit dan memperlambat proses pencarian data. Data berasal dari berbagai sumber dan administrator. Kemajemukan ini menciptakan tumpukan data dengan bermacam tipe yang memiliki standarnya sendiri, yang dapat berdampak pada integritas data. Oleh karena itu, tersedianya sebuah sistem informasi data pegawai sangat dibutuhkan. Dalam menyelesaikan masalah tersebut, penulis merancang pengembangan sistem menggunakan pemodelan Data Flow Diagram (DFD), Personal Home Page (PHP) dan XAMPP sebagai web server, menggunakan basis data dari MySQL, VS Code untuk pengkodean aplikasi, serta HyperText Markup Language (HTML) dan CSS untuk membuat tampilan aplikasi. Dengan adanya Sistem Informasi Pengelolaan Data Pegawai Pada Bagian Tata Pemerintahan SETDAKO Lhokseumawe ini, staff akan lebih mudah dan efisiensi dalam melakukan perekapan data pegawai.\r\n\r\nKata kunci: sistem informasi, data pegawai, web');
INSERT INTO `tb_judul` (`id_judul`, `judul`, `nama`, `nim`, `tahun`, `abstrak`) VALUES
(56, 'PERANCANGAN SISTEM INFORMASI ARSIP SURAT MENYURAT DI PERUM BULOG KANTOR WILAYAH SUMATERA UTARA', 'DEVIRA YUDA ARMAYA', 160170202, 2020, 'Banyak jumlah surat yang dibuat dan diterima dibagian administrasi tata usaha Perum BULOG Kantor Wilayah Sumut, sehingga pencarian data akan menjadi tidak efisien dalam hal waktu dan tenaga dengan menggunakan sistem manual. Sehingga pada saat ini diperlukan suatu sistem administrasi manajemen surat yang lebih terstruktur agar dapat mempercepat pencarian data yang ada dan pembuatan laporan, sehingga penulis merasa perlu merancang aplikasi Arsip Surat Menyurat yang dianggap perlu dan membantu pihak TU. Aplikasi ini dirancang menggunakan PHP dan MySQL. Karena berbasis web, aplikasi kearsipan ini mempunyai kemampuan, dapat diakses dimanapun, admin dapat mengelola dengan login user sehingga dapat melakukan menambah, mengedit, menghapus dan menyimpan surat masuk dan keluar, dapat melakukan pencarian surat masuk dan surat keluar berdasarkan pengirim dan perihal, hasil pencarian dapat dilakukan pengurutan berdasar id surat atau tanggal surat, serta dapat mencetak laporan. Hasil yang diperoleh dari implementasi aplikasi arsip surat menyurat ini yaitu memudahkan petugas TU dalam mengelola pengarsipan surat yang dulunya manual sekarang menjadi digital, serta sangat membantu para petugas dalam melakukan pembuatan surat di pihak tata usaha Perum BULOG Kantor Wilayah Sumut.\r\n\r\nKata Kunci: Arsip Surat, MySQL, PHP, TU'),
(57, 'RANCANG BANGUN SISTEM INFORMASI ABSENSI MENGGUNAKAN QR-CODE BERBASIS WEB PADA PT L-HIJRAH TOUR &amp; TRAVEL BUREAU', 'MHD KHAIRUL INSANI', 170170042, 2020, 'Absensi kehadiran pegawai merupakan faktor penting bagi sebuah instansi atau perusahaan untuk mencapai tujuan, hal ini berkaitan pada kedisiplinan dan berdampak pada kinerja dari masing-masing pegawai. Oleh karena itu, perlu adanya pendataan khusus untuk mencatat absensi kehadiran agar aktifitas kerja dapat tercatat secara realtime dan baik, salah satunya menggunakan teknologi komputer dimana penerapannnya aplikasinya berbasis website. Sistem Informasi ini dibangun dengan menggunakan bahasa pemrograman PHP dan menggunakan basis data MySQL untuk memudahkan dalam mendesain website sebagai media informasi dengan beberapa tahapan seperti analisa dan perancangan serta implementasi. Sistem Informasi Absensi Pegawai Berbasis QR dapat memberikan kemudahan dalam proses absensi pegawai, pencarian data pegawai dan perhitungan rekap absensi pegawai serta meminimalisir kehilangan dan kesalahan pencatatan data absensi pada PT L-Hijrah Tour & Travel Bureau.\r\n\r\nKata Kunci : Sistem Informasi, Absensi, QR'),
(58, 'Untuk Melengkapi Sebagian Dari Syarat-Syarat Akademik Yang Diperlukan Pada Fakultas Teknik Universitas Malikussaleha', 'MUKARRAMAH', 170170018, 2020, 'Inventaris adalah suatu kegiatan yang bertujuan untuk mengelola persediaan barang aset kantor atau perusahaan yang dimiliki. Dalam Penulisan ini memaparkan sebuah aplikasi berbasis web untuk membantu petugas dalam penginventarisan barang di PT Bank Rakyat Indonesia (Persero) Cabang Bireun dalam melakukan pendataan inventaris menjadi lebih efektif dan efisien. Sistem Informasi Inventaris Barang di Bank ini dirancang dengan menggunakan pemodelan DFD (Data Flow Diagram) dan Entity Relationship Diagram (ERD). Sedangkan bahasa pemrograman yang digunakan adalah PHP, HTML, JavaScript dan database MySQ. Hasil dari rancang bangun ini adalah Web Sistem Informasi Inventaris Barang di Bank yang berguna bagi admin untuk mengelola data pengadaan barang, mutasi barang, penginventarisan barang serta penghapusan barang.\r\n\r\nKeyword: Sistem, Inventaris, Barang'),
(59, 'APLIKASI MANAJEMEN ANGGARAN KEGIATAN BERBASIS WEB PADA DINAS PERTANIAN KABUPATEN ACEH TENGAH', 'JULIANTO', 170170037, 2021, 'Pada studi kali ini membahas tentang pencatatan anggaran kegiatan pada Dinas Pertanian Kabupaten Aceh Tengah yang dinilai masih kurang transparan dan tidak efisien. Hal ini dikarenakan dinas pertanian masih melakukan pencatatan anggaran dengan cara manual, yang kemudian data anggaran tersebut disimpan ke dalam excel. Dengan adanya masalah tersebut, maka penulis rasa perlu adanya sebuah sistem yang dapat membantu Dinas Pertanian Kabupaten Aceh Tengah untuk menciptakan suatu pencatatan manajemen anggaran yang lebih cepat, akurat, efisien dan transparan. Maka dari itu penulis membuat sebuah Sistem Manajemen Anggaran berbasis web. Dimana diharapakan nantinya aplikasi ini dapat membantu pihak dinas pertanian untuk mengoptimalkan proses pencatatan anggaran, sehingga admin atau pengguna dapat menjadi lebih cepat dan mudah dalam melakukan pencatatan anggaran dalam suatu kegiatan (acara). Metode pengumpulan data menggunakan metode observasi dan wawancara. Sistem ini menggunakan Database secara terpusat dan berbasis web dengan menggunakan bahasa pemrograman PHP dan MYSQL.\r\n\r\nKata Kunci: Aplikasi, Manajemen, Anggaran, Dinas, Database.'),
(60, 'APLIKASI MANAJEMEN ANGGARAN KEGIATAN BERBASIS WEB PADA DINAS PERTANIAN KABUPATEN ACEH TENGAH', 'JULIANTO', 170170037, 2021, 'Pada studi kali ini membahas tentang pencatatan anggaran kegiatan pada Dinas Pertanian Kabupaten Aceh Tengah yang dinilai masih kurang transparan dan tidak efisien. Hal ini dikarenakan dinas pertanian masih melakukan pencatatan anggaran dengan cara manual, yang kemudian data anggaran tersebut disimpan ke dalam excel. Dengan adanya masalah tersebut, maka penulis rasa perlu adanya sebuah sistem yang dapat membantu Dinas Pertanian Kabupaten Aceh Tengah untuk menciptakan suatu pencatatan manajemen anggaran yang lebih cepat, akurat, efisien dan transparan. Maka dari itu penulis membuat sebuah Sistem Manajemen Anggaran berbasis web. Dimana diharapakan nantinya aplikasi ini dapat membantu pihak dinas pertanian untuk mengoptimalkan proses pencatatan anggaran, sehingga admin atau pengguna dapat menjadi lebih cepat dan mudah dalam melakukan pencatatan anggaran dalam suatu kegiatan (acara). Metode pengumpulan data menggunakan metode observasi dan wawancara. Sistem ini menggunakan Database secara terpusat dan berbasis web dengan menggunakan bahasa pemrograman PHP dan MYSQL.\r\n\r\nKata Kunci: Aplikasi, Manajemen, Anggaran, Dinas, Database.'),
(61, 'SISTEM INFORMASI PENGELOLAAN INVENTARIS BARANG PADA KANTOR IMIGRASI KELAS II LHOKSEUMAWE', 'RAUZATUNNUR', 150170035, 2018, 'Perancangan Sistem Informasi Inventaris Barang Pada Kantor Imigrasi Kelas II Lhokseumawe sangat dibutuhkan untuk keperluan data barang-barang inventaris. Sistem lama yang ada diinstansi tersebut masih menggunakan cara manual sehingga kinerja sistem inventaris barang masih belum efesien dan belum optimal, dengan adanya sistem komputerisasi pada inventaris barang maka dapat membantu membuat laporan barang yang baru masuk, barang keluar ataupun barang rusak dan efisien penggunaan kertas pada kantor tersebut serta bisa mencetak laporan inventaris barang. Dari permasalahan tersebut, maka penulis membuat sebuah sistem informasi Inventaris Barang dengan menggunakan metode pengamatan dan pengumpulan data yang kemudian berlanjut kearah penggambaran diagram konteks, DFD, ERD, relasi antar tabel, desain input dan desain output dari sistem tersebut. Hasil yang penulis harapkan dari sistem informasi ini adalah dapat memberikan kemudahan bagi pegawai dalam melakukan pengelolaan inventaris barang di Kantor Imigrasi Kelas II Lhokseumawe sehingga kedepannya dapat terus dikembangkan.\r\n\r\nKata kunci: Sistem, Informasi, Diagram Konteks, DFD, ERD dan Database.'),
(62, 'SISTEM INFORMASI KELUAR - MASUK SURAT PENGADILAN NEGERI LHOKSEUMAWE KELAS IB', 'SURADIAN', 150170075, 2018, 'Sistem informasi surat masuk dan keluar di pengadilan negeri lhokseumawe Kelas I B masih manual Jadi untuk mendata dan mencari surat keluar masuk yang memang sudah ada di gudang (tempat penyimpanan) sangatlah sulit dikarenakan surat harus diperiksa secara manual. Sehingga pegawai Pengadilan Negeri Lhokseumawe Kelas I B untuk mengurangi kesalahan yang mungkin terjadi pada saat bekerja dan juga dapat memberikan informasi secara terkomputerisasi dan dapat mempercepat pekerjaan dalam pendataan serta memudahkan proses pencarian data surat keluar dan masuk yang ada di kantor.\r\n\r\nKata kunci: sistem, informasi, database, surat, pengadilan'),
(63, 'SISTEM INFORMASI INVENTARIS ALAT TULIS KANTOR (ATK) BERBASIS WEB PADA KANTOR BPJS KESEHATAN KANTOR CABANG LHOKSEUMAWE', 'HALIMATUN SAKDIAH', 150170054, 2018, 'Seiring dengan perkembangan zaman, kebutuhan akan teknologi informasi sangat dibutuhkan dalam berbagai sektor kerja guna mempermudah kerja dan memperoleh informasi serta data yang relevan, akurat dan efisien. Pada kantor BPJS Kesehatan Kantor Cabang Lhokseumawe, inventaris Alat Tulis Kantor (ATK) belum terorganisir dengan baik, dimana persediaan Alat Tulis Kantor (ATK) masih dilakukan secara manual, yaitu petugas masih mencatat barang yang masuk dan barang yang keluar pada selembar kertas. Pendataan data seperti ini dapat mempersulit petugas dalam pendataan dan pembuatan laporan, sehingga hal ini dapat memperlambat dan menghambat kerja, serta data dan informas: yang diperoleh kurang akurat, kurang efektif dan efisien. Oleh karena itu, dibutuhkan sebuah sistem yang memadai dalam sistem inventaris Alat Tulis Kantor (ATK), sehingga penulis mencoba membuat sebuah Sistem Informasi Inventaris Alat Tulis Kantor (ATK) Berbasis Web Pada Kantor BPJS Kesehatan Kantor Cabang Lhokseumawe yang lebih optimal dan terorganisir dengan baik. Langkah-langkah yang digunakan dalam penelitian ini adalah analisis kebutuhan, perancangan sistem dan pengujian sistem Perancangan sistem ini dirancang dengan menggunakan diagram terstruktur yaitu dengan Diagram Konteks, digram arus data atau disebut dengan Data Flow Diagram (DFD), Entity Relationship Diagram (ERD) dan perancangan database atau disebut desain file menggunakan MySQL. Sedangkan untuk pengumpulan data menggunakan cara dengan observasi, wawancara dan studi pustaka. Sedangkan untuk software menggunakan bahasa pemograman PHP/XAMPP Control Panel v3 21. Dengan pembuatan dan perancangan sistem informasi ini diharapkan mampu mengurangi masalah yang terjadi dalam pendataan data barang masuk dan barang keluar sertal membantuproses kerja dalam memperoleh informasi dan data yang relevan, akurat dan efisien.\r\n\r\nKata Kunci Sistem Informasi, Diagram Terstruktur, MYSQL, PHP XAMPP.'),
(64, 'PERANCANGAN SISTEM INFORMASI SURAT MASUK DAN SURAT KELUAR PADA PT. BANK NEGARA INDONESIA (PERSERO) Tbk KANTOR CABANG UTAMA KOTA LHOKSEUMAWE', 'FADHILA', 130170094, 2018, 'Sistem informasi surat mauk dan surat keluar pada perusahaan PT Bank Negara Indonesia (Persero) Tbk Kantor Cabang Utama Lhokseumawe sangat di butuhkan untuk keperluan kegiatan sehari-hari. Sistem lama masih menggunakan sistem manual sehingga kinerja sistem surat masuk dan surat keluar belum optimal. Padahal alah satu landasan visi dan misi instansi ini adalah mewujudkan sistem pelayanan yang terbaik, akurat dan tepat waktu Untuk mewujudkan visi dan misi itu, perlu tersedia informasi yang lengkap dan akurat dalam berbagai sumber informasi yang terpercaya salah satunya dengan cara sistem terkomputerisasi pada pendataan surat, untuk membantu menjalankan tugas pokok mewujudkan tugas dengan akurat dan tepat waktu. Maka, penulis membuat sistem informasi. Sistem informasi tersebut menggunakanmetode pengumpulan data yang kemudian berlanjut kearah penggambaran diagram konteks, DFD, ERD, relasi antar tabel dan rancangan desain input dan output dari sistem ini. Hasil yang penulis harapkan dari tulisan ini gambar perancangan sistem informasi surat masuk dan surat keluar pada perusahaan PT Bank Negara Indonesia (Persero) Tbk Kantor Cabang Utama Lhokseumawe yang terkomputerisasi sehingga dapat terus dikembangkan.\r\n\r\nKata Kunci : Diagram Konteks, DFD, ERD, Relasi Antar Tabel'),
(65, 'SISTEM INFORMASI WHISTLEBLOWING (PENGADUAN) PADA PT INDONESIA ASAHAN ALUMINIUM (PERSERO) KUALA TANJUNG', 'Amien Rais Alfattah', 160170035, 2019, 'Sistem Informasi Whistleblowing (Pengaduan) Pada PT INALUM (Persero) Kuala Tanjung merupakan suatu aplikasi yang dirancang dan dibuat untuk memudahkan para karyawan/staff pada PT Indonesia Asahan Aluminium (Persero) Kuala Tanjung dalam mengelola database pengaduan. Adapun tujuan dari penelitian ini adalah untuk mengetahui bagaimana merancang dan membuat suatu sistem informasi yang mampu mengurangi masalah yang terjadi dalam gratifikasi pada PT Indonesia Asahan Aluminium (Persero) Kuala Tanjung karena itu penulis mencoba membuat suatu Sistem Informasi Whistleblowing (Pengaduan) Pada PT INALUM (Persero) Kuala Tanjung Sistem ini sangat penting pengaduan karena dapat memudahkan para staff/karyawan dalam pengaduan tentang gratifikasi. Sistem informasi ini menggunakan metode pengumpulan data dan berlanjut ke penggambaran diagram konteks, ERD, DFD, dan tampilan desain input dan output dari sistem ini. Sistem ini menggunakan bahasa pemograman PHP.\r\n\r\nKata Kunci: Sistem Informasi, PHP, MySQL.'),
(66, 'SISTEM INFORMASI PENDATAAN PESERTA MAGANG BPJS KETENAGAKERJAAN CABANG LHOKSEUMAWE', 'KHAIRAT NUR', 170170030, 2020, 'Kantor BPJS Ketenagakerjaan Cabang Lhokseumawe adalah badan hukum publik yang melindungi tenaga kerja Indonesia dalam mengatasi masalah dan resiko masyarakat terkait hubungan kerja. Salah satu kegiatan yang dilakukan di kantor BPJS Ketenagakerjaan Cabang Lhokseumawe adalah masih melakukan pendataan untuk peserta magang secara manual. Pendataan yang secara manual tersebut membuat pembimbing peserta magang kesulitan dalam merekap data peserta magang. Oleh karena itu penulis ingin membuat sebuat sistem untuk mempermudah dalam melakukan pendataan peserta magang. Pembuatan sistem ini menggunakan MySQL sebagai perangkat lunak, PHP untuk bahasa pemograman dan untuk kode editornya menggunkan Sublime text. Sedangkan untuk perancangan sistem penulis menggunakan metode pengembangan Waterfall dan untuk pemodelan sistem menggunakan konsep Object Oriented Programming (OOP) dengan Unified Modeling Language (UML) yang terdiri atas use case, activity diagram dan class diagram. Dengan adanya sistem pendataan ini dapat mempermudah BPJS Ketenagakerjaan Cabang Lhokseumawe dalam melakukan rekap data peserta magang yang lebih optimal dan relevan sehingga mempermudah dalam mendata peserta magang.\r\n\r\nKata Kunci: Sistem Pendataan, BPJS Ketenagakerjaan'),
(67, 'PERANCANGAN SISTEM MONITORING JARINGAN PADA DINAS KOMUNIKASI DAN INFORMATIKA KOTA SUBULUSSALAM', 'SRI UNGSILAWATI BR BERUTU', 170170045, 2021, 'Semakin meningkatnya ukuran dan jumlah perangkat jaringan maka akan semakin kompleks masalah yang ada pada jaringan tersebut. Hal ini tentunya membutuhkan pengawasan secara terus-menerus terhadap seluruh perangkat jaringan untuk menjamin ketersediaan atau availability layanan Terdapat banyak. kesulitan yang dihadapi oleh administrator jaringan jika harus memantau seluruh jaringan berkaitan dengan performa, analisis dan kontrol beberapa komponen secara manual, terutama jika jaringan tersebut akan semakin berkembang. Simple Network Management Protocol (SNMP) adalah protokol aplikasi pada jaringan TCP/IP yang dapat digunakan untuk pengelolaan dan pemantauan sistem jaringan SNMP komputer. Hampir sem engan membangun sebuah aplikasi sistem monitoring peralatan jaringan telah mendukung penggunaan S untuk pemantauannya. Dengan mem berbasis web dengan menggunakan protokol SNMP, diharapkan dapat memudahkan administrator jaringan didalam melakukan monitoring dan menjaga availability atau ketersediaan layanan di dalam jaringan tersebut. Dengan menggunakan likasi berbasis web ini dapat memudahkan bagi seorang admin jaringan untuk melakukan monitoring terhadap agent yang tersebar diseluruh jaringan sehingga dapat menjaga ketersediaan atau availability dari jaringan tersebut. Keterbatasan teknisi yang dimiliki oleh Dinas Komunikasi dan Informatika Kota Subulussalam. mengakibatkan terkendalanya perbaikan jaringan yang ada. Akibatnya, banyak pekerjaan yang harus tertunda karena pemantauan masih dilakukan secara manual. Maka dari itu, diperlukan sebuah sistem baru untuk memudahkan pemantauan jaringan. Sistem monitoring jaringan yang berbasis web menjadi pilihan karena memudahkan untuk diakses serta open source. Hasilnya, teknisi lebih mudah dalam memantau keadaan jaringan pada komputer-komputer di Dinas Komunikasi dan Informatika Kota Subulussalam.\r\n\r\nKata kunci: monitoring, SNMP, administrator,server.'),
(68, 'PERANCANGAN SISTEM INFORMASI PEMBUATAN AKTA DI DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL ACEH BARAT', 'RUDI MAHENDRA', 150170050, 2018, 'Perancangan Sistem Informasi Pembuatan Akta adalah sebuah perancangan sistem informasi yang dapat membantu proses pelayanan pembuatan akta di kantor Dinas Keendudukan dan Pencatatan Sipil Aceh Barat. Sistem ini dapat membantu mulai dari penginputan data pelapor, data bayi dan data orang tua bayi sampai verifikasi pencetakan akta. Dengan membuat sistem ini berbasis web, tentu akan lebih memudahkan user agar dapat mengakses sistem ini secara cepat dan tepat. Selain bisa membantu proses pelaksanaan pembuatan akta, sistem ini juga bisa menjadi sebuah media penyimpanan data-data kutipan akta masyarakat sebelumnya. Ini akan sangat membantu jika user ingin laporan kegiatan-kegiatan terdahulu dengan bantuan sistem informasi pembuatan akta.\r\n\r\nKata kunci: sistem informasi, akta, user, web'),
(69, 'SISTEM INFORMASI PERKARA TINDAK PIDANA KHUSUS PADA KANTOR KEJAKSAAN NEGERI LHOKSEUMAWE', 'ARIF DARMANSYAH', 150170001, 2018, 'Sebagai salah satu bagian dari lembaga pemerintahan, penggunaan sistem informasi menjadi sangat penting dalam membantu kinerja Kejaksaan Negeri Lhokseumawe guna terselenggaranya pelayanan yang baik dan efektif kepada masyarakat. Adapun tugas utama Kejaksaan Negeri Lhokseumawe tidak terlepas dari aktifitas penanganan berkas perkara. Oleh karena itu tujuan dari penelitian ini adalah menghasilkan suatu sistem informasi yang dapat mempermudah mendata berkas perkara tindak pidana khusus di Kejaksaan Negeri Lhokseumawe. Adapun dalam perancangan sistem ini dimulai dengan membuat sistem baru Perancangan ini dimulai dari Diagram Konteks, Data Flow Diagram (DFD).Entity Relationship Diagram(ERD), desain input Output sebagai gambaran dasar sistem yang akan di bangun nantinya Sistem ini diharapkan dapat mempermudah staf bagian pidsus baik dalam melakukan pendataan perkara maupun pembuatan laporan data perkara di kantor Kejaksaan Negeri Lhokseumawe.\r\n\r\n\r\nKata Kunci: Sistem, Informasi, Database, DFD,ERD, PHP,MySQL'),
(70, ' PERANCANGAN JARINGAN HOTSPOT MENGGUNAKAN MIKROTIK PADA UPT TEKNOLOGI INFORMASI DAN KOMUNIKASI UNIVERSITAS MALIKUSSALEH', 'Yulita', 180170054, 0, ''),
(71, 'Di UPT TIK Universitas Malikussaleh terdapat layanan akses internet dimana seluruh kegiatan yang ada ditempat tersebut membutuhkan akses internet. Hotspot merupakan jaringan internet tanpa kabel dan bisa diakses oleh semua perangkat bahkan komputer desktop. Hotspot juga dapat digunakan sehari-hari dan dapat dilewati dari pusat trafik paket data dalam jumlah tertentu. Satuan kecepatan Hotspot per paket data adalah bit per detik (bps). Hotspot diukur batas kecepatan transfer dari jumlah konsumsi paket data per satuan waktu, serta kapasitas atau daya tampung kabel Ethernet disebut Bandwidth. Sampai saat ini, penggunaan jaringan Internet sesama pengguna dapat saling berebut paket ini tanpa berhenti dan tanpa batas, sehingga mengakses Internet akan terasa menyulitkan jika dipakai selamanya Tujuan dari penulisan laporan ini adalah untuk merancang. jaringan menggunkan mikrotik, dan mengkonfigurasi batas kecepatan internet mikrotik untuk memaksimalkan pengguna internet pada UPT TIK Universitas Malikussaleh. Perancanagan jaringan mikrotik sudah diketahui oleh manajemennya, untuk itu menggunakan Bandwidth dan Access Point Hotpsot dari Mikrotik RouterOS. Penulis berinisiatif untuk melakukan suatu perancangan jaringan Mikrotik pada UPT TIK Universitas Malikussaleh, caranya mendaftarkan melalui admin, admin membuat user hotspot, kemudian mengkonfigurasi kecepatan jaringan atau bandwidth dengan menggunakan aplikasi Winbox. Perancangan bangun jaringan ini diharapkan dapat membantu untuk mengoptimalkan badnwidth dari Mikrotik UPT TIK Universitas Malikussaleh.  Katakunci: Hotspot, MikrotikOS Bandwidth, AccesPoint', 'Di UPT TIK Universitas Ma', 123123123, 0, '');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id_admin`);

--
-- Indeks untuk tabel `tb_judul`
--
ALTER TABLE `tb_judul`
  ADD PRIMARY KEY (`id_judul`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `admin`
--
ALTER TABLE `admin`
  MODIFY `id_admin` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT untuk tabel `tb_judul`
--
ALTER TABLE `tb_judul`
  MODIFY `id_judul` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=75;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
